[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
  '@/library/=src/library/',
  '@ethereum-attestation-service/contracts/=lib/eas-contracts/contracts/',
]
