// Generates src/history.ts: every past event of the contract, taken from the
// block explorer, replayed through the normal handlers.
const fs=require('fs'); const {Interface}=require('ethers');
const [abiPath,logsPath,outPath,snap]=process.argv.slice(2,6);
const iface=new Interface(JSON.parse(fs.readFileSync(abiPath)));
const logs=JSON.parse(fs.readFileSync(logsPath));
const HANDLED=['Debt','Funded','LendRepaid','Lending','OwnershipTransferred','Paused','RoleAdminChanged','RoleGranted','RoleRevoked','TokenAdded','Unpaused','UserQuotaIncreaseRequest','UserQuotaChanged','UserQuotaSigned','Withdraw'];
function val(type,v){
  if(type==='address') return `ethereum.Value.fromAddress(Address.fromString("${v}"))`;
  if(type==='address[]') return `ethereum.Value.fromAddressArray([${v.map(a=>`Address.fromString("${a}")`).join(', ')}])`;
  if(type==='bool') return `ethereum.Value.fromBoolean(${v})`;
  if(type==='string') return `ethereum.Value.fromString(${JSON.stringify(v)})`;
  if(type==='bytes32') return `ethereum.Value.fromFixedBytes(Bytes.fromHexString("${v}"))`;
  let m=type.match(/^uint(\d+)$/);
  if(m) return Number(m[1])<=32 ? `ethereum.Value.fromI32(${v.toString()})` : `ethereum.Value.fromUnsignedBigInt(BigInt.fromString("${v.toString()}"))`;
  throw new Error('unhandled type '+type);
}
let lines=[]; const counts={}; const skipped={}; const used=new Set();
for(const l of logs){
  const topics=l.topics.filter(t=>t);
  let p; try{p=iface.parseLog({topics,data:l.data});}catch(e){p=null}
  if(!p){skipped[topics[0].slice(0,10)]=(skipped[topics[0].slice(0,10)]||0)+1;continue}
  if(!HANDLED.includes(p.name)){skipped[p.name]=(skipped[p.name]||0)+1;continue}
  counts[p.name]=(counts[p.name]||0)+1; used.add(p.name);
  const params=p.fragment.inputs.map((inp,i)=>`p("${inp.name}", ${val(inp.type,p.args[i])})`).join(', ');
  lines.push(`  handle${p.name}(changetype<${p.name}Event>(ev(${parseInt(l.blockNumber,16)}, ${parseInt(l.timeStamp,16)}, "${l.transactionHash}", ${parseInt(l.logIndex,16)}, [${params}])));`);
}
const names=[...used].sort();
const out=`// GENERATED by scripts/gen-history.js. Do not edit by hand.
//
// Every event the contract emitted before block ${snap}, taken from the Celo
// block explorer and replayed through the normal handlers when the subgraph
// starts. Events from block ${snap} on are indexed live.
//
// Why: a full re-index in Subgraph Studio drops a large part of the historical
// Celo events without reporting an error. See README.
import { Address, BigInt, Bytes, ethereum } from '@graphprotocol/graph-ts';
import {
${names.map(n=>`  ${n} as ${n}Event,`).join('\n')}
} from '../generated/ReFiMedLend/ReFiMedLend';
import {
${names.map(n=>`  handle${n},`).join('\n')}
} from './re-fi-med-lend';

const CONTRACT = Address.fromString("${process.argv[6]}");
const ZERO = Address.zero();
const NO_BYTES = Bytes.empty();

function p(name: string, value: ethereum.Value): ethereum.EventParam {
  return new ethereum.EventParam(name, value);
}

function ev(blockNumber: i32, timestamp: i32, txHash: string, logIndex: i32, params: ethereum.EventParam[]): ethereum.Event {
  let zero = BigInt.zero();
  let block = new ethereum.Block(NO_BYTES, NO_BYTES, NO_BYTES, ZERO, NO_BYTES, NO_BYTES, NO_BYTES, BigInt.fromI32(blockNumber), zero, zero, BigInt.fromI32(timestamp), zero, zero, null, null);
  let tx = new ethereum.Transaction(Bytes.fromHexString(txHash), zero, ZERO, null, zero, zero, zero, NO_BYTES, zero);
  return new ethereum.Event(CONTRACT, BigInt.fromI32(logIndex), BigInt.fromI32(logIndex), null, block, tx, params, null);
}

export function handleReplayHistory(_block: ethereum.Block): void {
${lines.join('\n')}
}
`;
fs.writeFileSync(outPath,out);
console.log(JSON.stringify({replayed:counts,skipped,total:lines.length}));
